// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: metrics_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float32                `protobuf:"fixed32,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage     float32                `protobuf:"fixed32,4,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	NetworkUsage  float32                `protobuf:"fixed32,5,opt,name=network_usage,json=networkUsage,proto3" json:"network_usage,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsData) Reset() {
	*x = MetricsData{}
	mi := &file_metrics_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsData) ProtoMessage() {}

func (x *MetricsData) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsData.ProtoReflect.Descriptor instead.
func (*MetricsData) Descriptor() ([]byte, []int) {
	return file_metrics_data_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsData) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *MetricsData) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricsData) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *MetricsData) GetDiskUsage() float32 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *MetricsData) GetNetworkUsage() float32 {
	if x != nil {
		return x.NetworkUsage
	}
	return 0
}

func (x *MetricsData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_metrics_data_proto protoreflect.FileDescriptor

const file_metrics_data_proto_rawDesc = "" +
	"\n" +
	"\x12metrics_data.proto\x12\x05proto\"\xcc\x01\n" +
	"\vMetricsData\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x02R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x04 \x01(\x02R\tdiskUsage\x12#\n" +
	"\rnetwork_usage\x18\x05 \x01(\x02R\fnetworkUsage\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestampBCZAgithub.com/RicardoCenci/iot-distributed-architecture/shared/protob\x06proto3"

var (
	file_metrics_data_proto_rawDescOnce sync.Once
	file_metrics_data_proto_rawDescData []byte
)

func file_metrics_data_proto_rawDescGZIP() []byte {
	file_metrics_data_proto_rawDescOnce.Do(func() {
		file_metrics_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_data_proto_rawDesc), len(file_metrics_data_proto_rawDesc)))
	})
	return file_metrics_data_proto_rawDescData
}

var file_metrics_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metrics_data_proto_goTypes = []any{
	(*MetricsData)(nil), // 0: proto.MetricsData
}
var file_metrics_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metrics_data_proto_init() }
func file_metrics_data_proto_init() {
	if File_metrics_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_data_proto_rawDesc), len(file_metrics_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_data_proto_goTypes,
		DependencyIndexes: file_metrics_data_proto_depIdxs,
		MessageInfos:      file_metrics_data_proto_msgTypes,
	}.Build()
	File_metrics_data_proto = out.File
	file_metrics_data_proto_goTypes = nil
	file_metrics_data_proto_depIdxs = nil
}
