// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: sensor_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Humidity      float32                `protobuf:"fixed32,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_sensor_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_sensor_data_proto_rawDescGZIP(), []int{0}
}

func (x *SensorData) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *SensorData) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *SensorData) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SensorData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_sensor_data_proto protoreflect.FileDescriptor

const file_sensor_data_proto_rawDesc = "" +
	"\n" +
	"\x11sensor_data.proto\x12\x05proto\"\x85\x01\n" +
	"\n" +
	"SensorData\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x1a\n" +
	"\bhumidity\x18\x02 \x01(\x02R\bhumidity\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampBCZAgithub.com/RicardoCenci/iot-distributed-architecture/shared/protob\x06proto3"

var (
	file_sensor_data_proto_rawDescOnce sync.Once
	file_sensor_data_proto_rawDescData []byte
)

func file_sensor_data_proto_rawDescGZIP() []byte {
	file_sensor_data_proto_rawDescOnce.Do(func() {
		file_sensor_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensor_data_proto_rawDesc), len(file_sensor_data_proto_rawDesc)))
	})
	return file_sensor_data_proto_rawDescData
}

var file_sensor_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sensor_data_proto_goTypes = []any{
	(*SensorData)(nil), // 0: proto.SensorData
}
var file_sensor_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sensor_data_proto_init() }
func file_sensor_data_proto_init() {
	if File_sensor_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensor_data_proto_rawDesc), len(file_sensor_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sensor_data_proto_goTypes,
		DependencyIndexes: file_sensor_data_proto_depIdxs,
		MessageInfos:      file_sensor_data_proto_msgTypes,
	}.Build()
	File_sensor_data_proto = out.File
	file_sensor_data_proto_goTypes = nil
	file_sensor_data_proto_depIdxs = nil
}
