{
 "title": "Sensor Data",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "Device",
    "query": "SELECT device_id from sensor_data GROUP BY device_id"
   }
  ]
 },
 "panels": [
  { "title": "Sensor Data By Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Humidade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iot_data2",
     "rawSql": "SELECT\n  AVG(humidity) as Avg,\n  time_bucket('1 minutes', \"time\") AS \"time\",\n  sensor_data.device_id,\n  MAX(humidity) as Max,\n  MIN(humidity) as Min\nFROM\n  sensor_data\nWHERE sensor_data.device_id = '$device_id' \nGROUP BY\n  sensor_data.device_id,\n  time_bucket('1 minutes', \"time\")\nORDER BY\n  time_bucket('1 minutes', \"time\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iot_data2",
     "rawSql": "SELECT\n  AVG(temperature) as Avg,\n  time_bucket('1 minutes', \"time\") AS \"time\",\n  sensor_data.device_id\nFROM\n  sensor_data\nWHERE sensor_data.device_id = '$device_id' \nGROUP BY\n  sensor_data.device_id,\n  time_bucket('1 minutes', \"time\")\nORDER BY\n  time_bucket('1 minutes', \"time\")"
    }
   ]
  },
  { "title": "Metrics By Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "metrics_worker_iot_device_cpu_usage_percent{device_id=\"$device_id\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "metrics_worker_iot_device_disk_usage_percent{device_id=\"$device_id\"}",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "metrics_worker_iot_device_memory_usage_percent{device_id=\"$device_id\"}",
     "legendFormat": "Network Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "metrics_worker_iot_device_memory_usage_percent{device_id=\"$device_id\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  { "title": "All Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Global Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iot_data2",
     "rawSql": "SELECT\n  AVG(humidity) as Avg,\n  time_bucket('1 minutes', \"time\") AS \"time\",\n  MAX(humidity) as Max,\n  MIN(humidity) as Min\nFROM\n  sensor_data\nGROUP BY\n  time_bucket('1 minutes', \"time\")\nORDER BY\n  time_bucket('1 minutes', \"time\")"
    }
   ]
  },
  {
   "title": "Global Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iot_data2",
     "rawSql": "SELECT\n  AVG(temperature) as Avg,\n  time_bucket('1 minutes', \"time\") AS \"time\"\nFROM\n  sensor_data\nGROUP BY\n  time_bucket('1 minutes', \"time\")\nORDER BY\n  time_bucket('1 minutes', \"time\")"
    }
   ]
  }
 ]
}