{
 "title": "System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Sensor Datapoints Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "dataset": "iot_data",
       "rawSql": "SELECT \n  time_bucket('1 second', \"time\") AS \"time\",\n  count(device_id)\nFROM sensor_data\nGROUP BY\n  1\nORDER BY\n 1\n"
      }
     ]
    },
    {
     "title": "Number of Rows in the Database",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "iot_data",
       "rawSql": "SELECT count(*) FROM sensor_data "
      }
     ]
    },
    {
     "title": "Sensor Data Database Size",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "iot_data",
       "rawSql": "SELECT hypertable_size('sensor_data')"
      }
     ]
    },
    {
     "title": "Devices in the Last 30s",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "iot_data",
       "rawSql": "SELECT \n  COUNT(DISTINCT device_id) AS active_devices_last_30s\nFROM sensor_data\nWHERE \"time\" >= NOW() - INTERVAL '30 seconds';"
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(rabbitmq_connection_incoming_bytes_total[$__rate_interval])",
       "legendFormat": "Incoming Data"
      }
     ]
    },
    {
     "title": "Messages Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum by(instance) (rate(rabbitmq_global_messages_received_total{protocol=~\"mqtt.*\"}[$__rate_interval]))",
       "legendFormat": "Messages Received"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "floor(increase(prometheus_http_requests_total{job=\"prometheus\"}[$__rate_interval])) > 0",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  }
 ]
}